---
title: "Viz2"
author: "Yunjia Liu"
date: "2024-10-01"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(patchwork)
library(haven)
```


```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = case_match(
      id, 
      "USW00094728" ~ "CentralPark_NY", 
      "USW00022534" ~ "Molokai_HI",
      "USS0023B17S" ~ "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```


```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(aplha = .3) +
  labs(
    title = "Temperature scatterplot",
    x = "Minimum Temp()",
    y = "Maximum Temp()",
    color = "Location",
    caption = "Weather data taken from rnoaa package for three stations."
  ) +
  scale_x_continuous(
    breaks = c(-15, 0, 20),
    labels = c("-15","0","20")
  )+
  scale_y_continuous(
    limits = c(0,30),
    transform = "sqrt"
  )
```


```{r}
ggp_scatterplot =
  weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(aplha = .3) +
  labs(
    title = "Temperature scatterplot",
    x = "Minimum Temp()",
    y = "Maximum Temp()",
    color = "Location",
    caption = "Weather data taken from rnoaa package for three stations."
  ) +
  viridis::scale_color_viridis(discrete = TRUE)  #scale_color_hue(h = c(10,400))
```


## Theme

```{r}
ggp_scatterplot +
  theme(legend.position = "bottom")
  
```

```{r}

ggp_scatterplot +
  theme_bw() + # be consistent with the black and white theme, the order of these two lines matters 
  theme(legend.position = "bottom")
```


```{r}
ggp_scatterplot +
  theme(legend.position = "bottom") +
  gthemes::theme_excel()
```


```{r}
ggplot(weather_df, aes(x = date, y = tmax, color = name)) + 
  geom_smooth(se = FALSE) + 
  geom_point(aes(size = prcp), alpha = .75) + 
  labs(
    title = "Temperature plot",
    x = "Date",
    y = "Maxiumum daily temperature (C)",
    color = "Location",
    caption = "Data from the rnoaa package"
  ) + 
  viridis::scale_color_viridis(discrete = TRUE) + 
  theme_minimal() + 
  theme(legend.position = "bottom")
```

```{r}

weather_df |>
  ggplot(aes(x = tmax,fill = name))
```

### patchwork
```{r}
ggplot_tmax_tmin =
  weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name))+
  geom_point(alpha = .3) +
  theme(legend.position = "none")

ggplot_tmax_density =
  weather_df |>
  ggplot(aes(x= tmax, fill = name))+
  geom_density(alpha = .3) +
  theme(legend.position = "none")

ggplot_tmax_date =
  weather_df |>
  ggplot(aes(x = date, y = tmax, color = name))+
  geom_point()+
  geom_smooth(se = FALSE) +
  theme(legend.position = "bottom")

(ggplot_tmax_tmin + ggplot_tmax_density) / ggplot_tmax_date
```


### Data Munipulation
```{r}
weather_df |>
  mutate(name = fct_relevel(name, c("Molokai_HI", "CentralPark_NY", "Waterhole_WA"))) |>
  ggplot(aes(x = name, y = tmax, fill = name)) +
  geom_violin(alpha = .5) +
  theme(legend.position = "bottom")
```

P
```{r}
pulse_df = 
  read_sas("./data/public_pulse_data.sas7bdat") |>
  janitor::clean_names() |>
  pivot_longer(
    cols = bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    values_to = "bdi_score",
    names_prefix = "bdi_score_"
  ) |>
  mutate(visit = ifelse(visit == "bl","00m",visit))

pulse_df |>
  ggplot(aes(x = visit , y = bdi_score)) +
  geom_boxplot()
```



```{r}

pup_data = 
  read_csv("./data/FAS_pups.csv", na = c("NA", ".", "")) |>
  janitor::clean_names() |>
  pivot_longer(
    pd_ears:pd_walk,
    names_to = "outcome",
    values_to = "pn_day",
    names_prefix = "pd_"
  )


litter_data = 
  read_csv("./data/FAS_litters.csv", na = c("NA", ".", "")) |>
  janitor::clean_names() |>
  separate(group, into = c("dose", "day_of_tx"), sep = 3)

fas_df = left_join(pup_data, litter_data, by = "litter_number") 

fas_df |>
  drop_na(day_of_tx) |>
  ggplot(aes(x= dose, y =pn_day))+
  geom_boxplot() +
  facet_grid(day_of_tx ~ outcome)

```

